### ISSUE TITLE
Prettify the generated code

### ISSUE THREAD

**Issue by maticzav** [maticzav/swift-graphql#10]
Current code that the generator spits out is not properly formatted - indentation is misplaced, newlines are not optimally placed. We should format the code before we print it to a destination file.

**Comment by maticzav** [comment]
- [swift-syntax](https://github.com/apple/swift-syntax)
- [swift-format](http://github.com/apple/swift-format)

**Comment by maticzav** [comment]
```
Undefined symbols for architecture x86_64:
  "_$s11SwiftFormat0A9FormatterC13configuration16diagnosticEngineAC0aB13Configuration0G0V_0A6Syntax010DiagnosticF0CSgtcfC", referenced from:
      _$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o
  "_$s11SwiftFormat0A9FormatterC6format6source15assumingFileURL2toySS_10Foundation0H0VSgxztKs16TextOutputStreamRzlF", referenced from:
      _$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o
  "_$s11SwiftFormat0A9FormatterCMa", referenced from:
      _$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o
  "_$s24SwiftFormatConfiguration0C0VACycfC", referenced from:
      _$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o
ld: symbol(s) not found for architecture x86_64
```

> We are getting this error at the moment. I've added a list of possible leads for investigation.

- https://bugs.swift.org/browse/SR-9038?jql=component%20%3D%20SwiftSyntax
- https://github.com/SwiftDocOrg/swift-doc/issues/197

**Comment by Amzd** [comment]
If anyone lands here in the future from google; Instead of trying to figure out the errors we switched to using https://github.com/nicklockwood/SwiftFormat.
