### ISSUE TITLE
Looking for Co-Maintainer  👋 

### ISSUE THREAD

**Issue by maticzav** [maticzav/swift-graphql#100]
Hi everyone 👋 ,

I am Matic (Matt), the creator of `swift-graphql` and I am looking for someone to help me work on the library.

I am looking for someone who is a seasoned Swift developer and would also be interested in promoting the project by speaking at the conferences. I'd help with the direction of the library, the code quality standard and programming, and you'd do everything that sounds fun to you.

I can only offer much besides public endorsement, gratefulness and loads of fun, (and possibly some swag 😎).

Let me know if you'd be interested and let's start collaborating! 😄

**Comment by rushairer** [comment]
Hand up~

**Comment by BerkeleyTrue** [comment]
@maticzav I'd be interested in help as well.

**Comment by BerkeleyTrue** [comment]
I also like this framework for contributing to increase or spread maintenance work out  
https://openopensource.github.io/

**Comment by maticzav** [comment]
👋 thank you for being so patient with me. I hope you are still interested in co-maintaining this library! 🙂 

I was going through your sites and couldn't find a way to connect so feel free to add me on Discord (maticzav [hhashh] 0744) or Telegram (at maticzav).

Exciting!

**Comment by maticzav** [comment]
To shed more light on the state of this library, I am still actively submit fixes and helping out with the community but I don't have the capacity to take on new features and DX improvements.

**Comment by pokryfka** [comment]
@maticzav what is the status of the library?

I like a lot how I can reuse fragments in Swift (unlike in Apollo iOS codegen) but I am worried that this library is not maintained at all.

Any change to have, at least, bug fixed, for example #124

**Comment by maticzav** [comment]
Hey @pokryfka 👋 ,

Thank you for the kind words. The library is working and I am actively developing it, but it's not a high priority. As mentioned above I am looking for a co-maintainer or a more fixed source of sponsorship/partnership that would allow me to focus more time on the development.

My experience so far has been very positive. I think lots of issues that are opened also get resolved either by me or by someone in the community. I am always happy to give guidelines and discuss solutions. The code is well documented and it shouldn't be hard to navigate around it. It's also very modular so you could use certain parts and leave other parts out.

Regarding fixing issues; I love every single issue and I also find them very interesting. The one that you referenced doesn't have much content yet so it's hard for me to "just fix it". I need to first reproduce it, write tests, etc. etc.. Whenever someone in the community takes time to handle one of the parts (e.g. creates a reproduction repository with actual code and even records a video explaining what's happening) I try to pick up their work and resolve it in the course of that week.

**Comment by shaps80** [comment]
@maticzav Hey there 👋

I’m the iOS lead at GeoBrowser, our founder (Yaniv) mentioned you may have a relationship with The Graph which he originally founded.

Regardless I’m now looking for a GraphQL solution for the iOS/macOS project and he mentioned this project. I was skeptical at first for a lot of the same reasons you raised here https://the-guild.dev/blog/swift-graphql

However after reviewing the code and that page, I feel you’ve hit the nail on the head and come up with a great solution.

If we adopt this library we’ll need to ensure its well supported and would be interested in longer term contributions given this would serve both our needs.

From the title on this ticket, it sounds like this would also align with your needs and as an extremely active open source contributor myself, for over a decade, I understand the effort that goes into maintaining even a single project 👍🏻

You’ve done an amazing job!

> Side note, I really want the `async` PR haha, that’d definitely be my first priority.

Anyway, I’d love to hear your thoughts and ideally if we can become contributors that could help you out while enabling us to adopt your creation without the need to fork and maintain a separate working copy.

**Comment by pokryfka** [comment]
@shaps80 @maticzav 

The way I see it - its a great idea and a nice library but, sadly, its dead.

@shaps80 if you have a capacity to make and maintain a fork I shall be able to help with some work.

**Comment by maticzav** [comment]
@pokryfka thank you for the ping. We had a chat and agreed on co-maintaining. I just had a stressful month and I am trying to dig back in 🙂

**Comment by shaps80** [comment]
@pokryfka As mentioned by Mat I'm now a __co-maintainer__ and in fact I'm going to get almost all of the current PRs merged this week!

In addition I have some ideas/plans moving forward that will hopefully bring it "back from the dead?" 😆 – Look out for these in the Discussions initially.

In addition, my team and I are going to be using this library to support a couple of applications so you should see more consistent output moving forward.

Its a fantastic approach and @maticzav has done an amazing job imo. Its not easy maintaining an open source library for as long as he has, but with the codebase, docs, website and everything else, this has more opportunity than most to establish itself further.

See you in the discussions ;)

**Comment by pokryfka** [comment]
Happy to hear that!
