### ISSUE TITLE
Package resolution error due to unstable version of swift-format

### ISSUE THREAD

**Issue by clayellis** [maticzav/swift-graphql#110]
**Describe the bug**
Adding swift-graphql as a package dependency results in this error:

> Failed to resolve dependencies. Dependencies could not be resolved because 'my-package' depends on 'swift-graphql' 4.0.4..<5.0.0.
'swift-graphql' >= 4.0.4 cannot be used because package 'swift-graphql' is required using a stable-version but 'swift-graphql' depends on an unstable-version package 'swift-format' and no versions of 'swift-graphql' match the requirement 4.0.5..<5.0.0.

**To Reproduce**

1. Create a new Swift package.
2. Add swift-graphql as a package dependency. `.package(url: "https://github.com/maticzav/swift-graphql/", from: "4.0.4")`
3. Observe the error in package resolution.

**Expected behavior**
Adding a tagged release of swift-graphql should not result in package resolution errors.

**Additional context**
This appears to be due to swift-graphql depending on the `main` branch of `swift-format` rather than a tagged release.

**Comment by Sundea** [comment]
BTW, swift-format is needed for CLI library and codegen. @maticzav does it really need to have a single package for multiple destinations MacOS and iPhoneos?

**Comment by maticzav** [comment]
I suppose this should be resolved by https://github.com/maticzav/swift-graphql/commit/3e26d207d410c1ec7e5f93ddab82361018e24c27. Feel free to reopen if this is still relevant.

@Sundea I am not sure I understand what you are proposing. Could you explain what you see as an alternative? I'd love to improve the packaging if you know of a clever way.
