### ISSUE TITLE
StringIndexValidation.swift:120: Fatal error: String index is out of bounds

### ISSUE THREAD

**Issue by kanstantsin-bucha** [maticzav/swift-graphql#113]
Hi! 
I need help, an idea of what can be wrong with schema.

I installed the tool using `brew`
then I tried to generate a code for my local graphql server
code generation fails
```
SwiftGraphQL % swift-graphql http://127.0.0.1:3001/graphql --output ./output
Generating SwiftGraphQL Selection 🚀
✔ Schema loaded!
⠋ Generating APISwift/StringIndexValidation.swift:120: Fatal error: String index is out of bounds
```

I am not common with `/graphql` endpoint protocol and it might be the server setup is not right. I managed to use it with apollo but there can be a hidden issue.
I get the error During the code generation phase
I attached schemas from the playground to the issues. it might be connected to this part that autogenerated by Apollo for some reason
```
# The `Upload` scalar type
 represents a file upload.
scalar Upload
```

**To Reproduce**

1. clone https://github.com/kanstantsin-bucha/swift-playgrounds
2. navigate to _GraphQL/graphql-apollo-api-part1
3. run `npm start`
4. run `swift-graphql http://127.0.0.1:3001/graphql --output ./output`

**Expected behavior**
Code is generated.

**Desktop (please complete the following information):**

- OS: MacOS 13.1 (22C65)
- Version 4.0.4
[schemas.zip](https://github.com/maticzav/swift-graphql/files/10518719/schemas.zip)

**Comment by maticzav** [comment]
Thank you for opening the issue! Could you help me understand your use of `_` in `Mutation` model?

```graphql
type Mutation {
  _: String
  createTask(input: createTaskInput!): Task
}
```

Is this a common practice or some trick?

**Comment by kanstantsin-bucha** [comment]
This issue occurs when I was learning the GrapQL myself. I was using an example from the course from Skillshare. Let me remind myself why they use that, and I will post it here.

**Comment by kanstantsin-bucha** [comment]
Thank you for waiting.
I rewatched the lesson from [Skillshare](https://www.skillshare.com/en/classes/GraphQL-Apollo-Server-with-Node-js-MongoDB-GraphQL-API/294276149/projects?via=search-layout-grid) 
I see that these placeholders were created during schema Modularisation process, when the root schema was created with all types declaration, but description of each type moved into separate file (using **extend type** syntax).
<img width="1430" alt="Screenshot 2023-04-25 at 11 47 45" src="https://user-images.githubusercontent.com/16370048/234242215-7b345f80-8979-4133-97f6-e04b02c24d0a.png">
<img width="998" alt="Screenshot 2023-04-25 at 11 55 26" src="https://user-images.githubusercontent.com/16370048/234242259-99aa9037-06e2-4e43-ac7c-73b6aec4e777.png">

Can you confirm  that these '_: String' declarations is a root source of the issue?

**Comment by shaps80** [comment]
@kanstantsin-bucha this past week I merged in some changes that we believe _may_ have been causing this issue. If you are able to re-test and report back I'd really appreciate it 👍
