### ISSUE TITLE
Failing to resolve dependencies for 4.1.0

### ISSUE THREAD

**Issue by NeverwinterMoon** [maticzav/swift-graphql#119]
![image](https://user-images.githubusercontent.com/1917308/229431882-4a589fba-7d56-4dbe-815e-b840da68fae6.png)

I assume it's because of this: 
`.package(url: "https://github.com/apple/swift-format", branch: "main"),`

As this is pointing to a branch instead of a stable release.

**Comment by maticzav** [comment]
Thank you for opening this issue and reporting it. 

I think swift-format's wording [changed](https://github.com/apple/swift-format/commit/eae9b782e5fff783a7c007f20b683c1c03cb608b) since I set the package to follow the `main` branch.

Will release the new version in a moment.
