### ISSUE TITLE
Discussion: Subscriptions

### ISSUE THREAD

**Issue by Amzd** [maticzav/swift-graphql#12]
This project looks very good and I'd love to use it but I also need subscriptions. 

Did you already have a rough idea on how to implement this? So I am not doing the same work twice.

**Comment by maticzav** [comment]
Thanks! I have no idea how to implement subscriptions yet. My suggestion would be that you open up an RFC in discussions and outline your suggested approach and thinking, we can discuss the API and possibly work on the implementation. In terms of ETA (from my side) this should be up and running before the end of February, but I do need some help with implementation and WS support in Swift.

**Comment by Amzd** [comment]
Agreed, I didn't know what the best way was to contact you. Didn't know about discussions, will continue there.
