### ISSUE TITLE
DebugExchange's usage of Logger is a bit counterintuitive

### ISSUE THREAD

**Issue by NeverwinterMoon** [maticzav/swift-graphql#121]
Default instance (defaults to `debug = True`) of `DebugExchange` will use `Logger#debug`. Yet, default `SwiftGraphQLClient.Client`'s configuration initializes logger with `logLevel` that does not include `debug`. This means that just adding `DebugExchange` to the list of client's exchanges will not enable logs from that exchange. This is a bit confusing.

Right now, in addition to having `DebugExchange`, I needed to do something like this:
```swift
var config = SwiftGraphQLClient.ClientConfiguration()
config.logger.logLevel = .debug

SwiftGraphQLClient.Client(
  request: request,
  exchanges: exchanges,
  config: config
)
```

**Comment by maticzav** [comment]
Great catch, thanks!

Do you by chance have a minute to also prepare a PR for it? I'd be more than happy to immediately merge it in 😄
