### ISSUE TITLE
Memory consumption gradually increasing

### ISSUE THREAD

**Issue by takuo3** [maticzav/swift-graphql#124]
**Describe the bug**
I am encountering an issue with memory consumption gradually increasing when using SwiftGraphQL in my app development.

**To Reproduce**

Use the sample app GithubStars
Modify the FetchExchange.register() by adding a code snippet to prevent actual requests from being sent (memory usage increases regardless of whether requests are sent or not)
Record a video demonstrating the increase in All Heap & Anonymous VM 

**Expected behavior**
The memory consumption should remain constant, without any leaks or increases.

**Screenshots**
https://user-images.githubusercontent.com/100672283/235578976-68fc80f8-8b38-43db-bbf3-9d8ba2b7128a.mov

**Desktop (please complete the following information):**
(None)

**Smartphone (please complete the following information):**

Device: Simulator (iPhone 14 Pro)
OS: iOS 16.4

**Additional context**
I added a code snippet to the following part of GithubStars' FetchExchange.register() to prevent actual requests from being sent:

```
public func register(
    client: GraphQLClient,
    operations: AnyPublisher<Operation, Never>,
    next: ExchangeIO
  ) -> AnyPublisher<OperationResult, Never> {
    let shared = operations.share()

    let downstream = shared
      .filter { operation in
        operation.kind != .query && operation.kind != .mutation
      }
      .eraseToAnyPublisher()

    let upstream = next(downstream)

    let fetchstream = shared
      .filter({ $0.kind == .query || $0.kind == .mutation })
      .flatMap({ operation -> AnyPublisher<OperationResult, Never> in
        let body = try! self.encoder.encode(operation.args)

        // added ↓
        if operation.types.contains(where: { $0 == "User" }) {
          let result = OperationResult(
            operation: operation,
            data: nil,
            errors: [.network(URLError(.cancelled))],
            stale: false
          )
          print("Abort request")
          return Just(result).eraseToAnyPublisher()
        }
        // added ↑

        let torndown = shared
          .filter { $0.kind == .teardown && $0.id == operation.id }
          .eraseToAnyPublisher()
```
If you have any suggestions or solutions for this issue, please let me know. Thank you very much for your assistance.

**Comment by shaps80** [comment]
@maticzav / @takuo3 – is this an issue we still need to investigate and/or resolve?

I'm just cleaning up the issues so we can determine priority etc thanks!

**Comment by shaps80** [comment]
I am not seeing other reports and tbh v6 plans should either resolve or re-introduce this issue (hope not lol) in a completely different way. So for now, I'm going to close this issue to keep us focused.

If you happen to uncover deeper details that would enable us to investigate further, please feel free to comment again 👍
