### ISSUE TITLE
CODEGEN: Deprecation messages are not escaped and cause failure.

### ISSUE THREAD

**Issue by thingdeux** [maticzav/swift-graphql#130]
## Explanation
If a deprecated GraphQL type includes a description string that contains quotes - those quotes are not escaped during codegen.

An example use case can be seen here: 
https://github.com/apollographql/apollo-ios/issues/2879

**Comment by thingdeux** [comment]
Related issue -> [#129](https://github.com/maticzav/swift-graphql/issues/129) with the error output.  
Swift-Format throws an exception and the codegen exits with failure.

Once I removed the format step from the generation job I could run swift-format manually and take a peek at the error.  At which point I found that it was the deprecation messages not escaping their quotes.

**Comment by maticzav** [comment]
Thank you!
