### ISSUE TITLE
Cannot handle grapqhl error properly because client is returning `DecodingError.keyNotFound`

### ISSUE THREAD

**Issue by rantingmong** [maticzav/swift-graphql#133]
**Describe the bug**
I'm trying to send a graphql request but when my query returns this response:
```
{
  "errors": [
    {
      "extensions": {
        "code": "unexpected",
        "path": "$"
      },
      "message": "Incorrect username or password."
    }
  ]
}
```

The client just returns a `CombinedError.unknown(DecodingError.keyNotFound)`. Instead of returning the error described in the response object.

Take note that the GraphQL server is running on Hasura and my graphql selector is shaped as:
```
Selection.QueryRoot<Auth.Session> {
  try $0.login(
    email: emailAddress,
    password: password,
    selection: SelectorSessionResponse.nonNullOrFail
  )
}

let SelectorSessionResponse = Selection.SessionResponse {
    Auth.Session(
        accessToken: try $0.accessToken(),,
        expiresIn: try $0.expiresIn(),
        user: Auth.User(
            uid: try $0.uid()
        )
    )
}

```

**Comment by maticzav** [comment]
Thank you for reporting the issue. Could you describe what your schema looks like and what you were expecting?

**Comment by maticzav** [comment]
I think this was related to #144.
