### ISSUE TITLE
Error installing 5.0.1

### ISSUE THREAD

**Issue by robsontenorio** [maticzav/swift-graphql#136]
**Describe the bug**
It not installs on fresh project with 5.0.1.

**To Reproduce**

1. Create a fresh project
2. Add `https://github.com/maticzav/swift-graphql/`

<img width="767" alt="image" src="https://github.com/maticzav/swift-graphql/assets/118955/cfe89ff4-65b1-436d-abe5-a721bfdc5260">

**Expected behavior**
Should install with success

**Screenshots**
<img width="799" alt="image" src="https://github.com/maticzav/swift-graphql/assets/118955/2fb79ca1-5fe0-48c1-a4f8-0f3347b5207e">

**Desktop (please complete the following information):**

- OS: macOs, iOS, XCode
- Version: 13.3 / 16.4 / 14.3

<img width="779" alt="image" src="https://github.com/maticzav/swift-graphql/assets/118955/2fc09ddb-7952-476b-93f6-36a12552c5eb">

**Comment by robsontenorio** [comment]
Just spotted the issue.... Any workarounds?

<img width="670" alt="image" src="https://github.com/maticzav/swift-graphql/assets/118955/4d2c73b2-a32e-4a69-88bf-c05529341ad1">

**Comment by pokryfka** [comment]
There is no reason to run `swift-graphql` on iOS, is there?
