### ISSUE TITLE
Non 200 http responses are ignored when handling a response

### ISSUE THREAD

**Issue by bradleyrzeller** [maticzav/swift-graphql#154]
**Describe the bug**
The `FetchExchange` [ignores the http status code](https://github.com/maticzav/swift-graphql/blob/1fcd18c0d1853298180702f756b88a5d18d57481/Sources/SwiftGraphQLClient/Exchanges/FetchExchange.swift#L83) of a response and always attempts to decode the result, leading to incorrect error reporting. The [spec states](https://github.com/maticzav/swift-graphql/blob/1fcd18c0d1853298180702f756b88a5d18d57481/Sources/SwiftGraphQLClient/Exchanges/FetchExchange.swift#L83) that non 200 responses should not be expected to be well-formed graphql so I _think_ this is a valid expectation of mine.

I've read the release notes on the last several versions and looks like error handling has been tweaked lately, even mentioning how auth related errors are typically handled before requests reach the gql layer of the server. However, non 200 http response statuses are still ignored (tested in 5.0.7). Am I misunderstanding something? 

If this is in fact a valid bug, I'd be happy to open a PR but wanted to confirm my understanding before doing so. Thanks!

**To Reproduce**
Return a non-200 http code (e.g. 401) with an empty body from the server. Upon making a request, the client will emit an `.unknown(Swift.DecodingError)`error  instead of a more correct error (e.g. like an `HttpError`).

**Expected behavior**
I would expect http errors to be thrown rather than a "decoding error" upon non-200 responses.

**Additional context**
* package version: 5.0.7

**Comment by shaps80** [comment]
@bradleyrzeller 
Since this is now a few months old, can you clarify if this issue still exists? I'm just cleaning up the issues so I know what to focus on 👍

**Comment by shaps80** [comment]
Could you post the exchange code on this issue? And highlight (in comments) the changes you required, as well as specific expectations?

I know that could be time-consuming but it'd really help me understand more context and determine an appropriate way forward 👍

**Comment by bradleyrzeller** [comment]
I'm pretty sure this is the only change I made (inserted [here](https://github.com/maticzav/swift-graphql/blob/ab840d97be194c6888e996c68182a84cff097cf2/Sources/SwiftGraphQLClient/Exchanges/FetchExchange.swift#L83), just before decoding):

```
guard let response = response as? HTTPURLResponse else { throw GenericError("Unexpected response type") }
guard (200 ..< 300).contains(response.statusCode) else {
    throw HTTPError(statusCode: response.statusCode)
}
```

My expectations would be that http status errors be propagated out of the client and that _decoding_ is only attempted when the http status is a 200. 

The way it works now (always throwing a decoding error) makes it impossible for clients of the `GraphQLClient` to do things like auth error handling (e.g. expired token / 401 etc.).

**Comment by shaps80** [comment]
I see, that's basically what I expected actually.
I get it, I'll take a look into this while planning updates, thanks for clarifying 👍

**Comment by shaps80** [comment]
Given the above context and current limitations I'm going to close this issue. However just FYI I feel this is an important "fix" that definitely needs to be considered, I'll be including this issue as a reference in upcoming designs for v6 that could not only resolve this issue but lastly improve error handling in general 👍
Thanks!
