### ISSUE TITLE
Add support for AWS AppSync

### ISSUE THREAD

**Issue by pokryfka** [maticzav/swift-graphql#158]
Subscriptions dont not work on some servers (example: AWS AppSync) because `GraphQLWebSocket` implements deprecated `subscriptions-transport-ws` protocol.

See [subscriptions-transport-ws is no longer maintained](https://github.com/apollographql/subscriptions-transport-ws#subscriptions-transport-ws-is-no-longer-maintained)

**Comment by Amzd** [comment]
I know the new and old protocol are easily confused as the WebSocket sub-protocol for the old protocol is `graphql-ws` which is the repo name of the new one but this library uses the new one.

https://github.com/maticzav/swift-graphql/blob/1fcd18c0d1853298180702f756b88a5d18d57481/Sources/GraphQLWebSocket/Spec.swift#L18

https://github.com/enisdenjo/graphql-ws/blob/50d5a512d0d7252d41c079e6716b884a191b1ddc/PROTOCOL.md?plain=1#L10

**Comment by pokryfka** [comment]
Fair enough and thank you for clarifucation, new or old it does not work with [AWS AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html) which for me personally is a blocker.

I will have a look at the differences and try to make it working.

Please let me know if you think adding AppSync support should/could be added to the main repository; otherwise I will just keep it on my fork.

**Comment by Amzd** [comment]
Yeah if I understand the linked doc correctly, AWS AppSync is not really GraphQL, it just has a GraphQL interface for queries and mutations. Not sure why they decided to create their own websocket protocol for subscriptions but implementing it seems a bit out of scope for this repo.

**Comment by pokryfka** [comment]
I am not expert on the topic but [enisdenjo](https://twitter.com/enisdenjo) does not seem very authoritative to me. I was trying to find "official specification" but the specification on [https://spec.graphql.org](https://spec.graphql.org/draft/#sec-Subscription-Operation-Definitions) does not include transport protocols.

FYI I made it working with AppSync with a few changes; the the way it works almost exactly the same way, just the types of the messages are slightly different, for example `start` instead of `subscribe`; also the payload of `start` is slightly different and AppSync keeps sending `ka` (keep alive) message instead of ping-ponging.

**Comment by shaps80** [comment]
@pokryfka from the context above I'd agree it sounds out-of-scope for this library.

However, I'm keen to understand how this library blocked your implementation – perhaps we need to improve existing (or provide new) abstractions to ensure "plug-n-play" works in other contexts like yours.

Could you link to your fix and perhaps add more detail here explaining exactly what was preventing you initially and what you did to resolve it.

That will inform me enough to determine if there are changes and/or abstractions that could ensure you (and others?) don't need to resort to their own forks which is problematic and obvs not ideal.

Thanks!

**Comment by pokryfka** [comment]
There are a few different transport protocols for subscriptions via websockets.

This library supports one of them (used by Apollo server), AWS AppSync (which is another GraphQL server implementation) uses different protocol.

**Comment by shaps80** [comment]
Ok I'll close this for now and if it gets more attention we can consider it but I feel we have other priorities that are more far reaching atm.
