### ISSUE TITLE
Does Query Builder support multi-operation queries?

### ISSUE THREAD

**Issue by pokryfka** [maticzav/swift-graphql#160]
Does Query Builder support multi-operation queries like:

```
query GetMyProfileAndBadge {
  getMyProfile {
    screenName
    picture {
      url
    }
  }
  getMyGameStats {
    badge
  }
}
```

another example with aliases - query for the same field with different arguments, see https://graphql.org/learn/queries/#aliases

```
{
  empireHero: hero(episode: EMPIRE) {
    name
  }
  jediHero: hero(episode: JEDI) {
    name
  }
}
```

**Comment by shaps80** [comment]
I'm taking a look at this atm because I have a similar requirement. I'll post any updates next week 👍
