### ISSUE TITLE
Multiple variables with the same value in GraphQL request ends up failing

### ISSUE THREAD

**Issue by justvil** [maticzav/swift-graphql#17]
**Describe the bug**
If passing two identical strings as parameters to a mutation, the final POST body being sent seems to be optimized to a single variable, which produces an error in our GraphQL server.

I'm passing email and password as two identical parameters "asd".

Here's the query payload that's being sent to our server:

```
{
  "query”: “mutation ($__i6uv6ixjnetj: String!, $__i6uv6ixjnetj: String!)
  {
    createUser__bm9w5hv7q7ub: createUser(email: $__i6uv6ixjnetj, password: $__i6uv6ixjnetj)
    {
      __typename
      success___9371xkl2k0n: success
      error___9371xkl2k0n: error
      userId___9371xkl2k0n: userId
    }
  }“,
  “variables“:
  {
    “__i6uv6ixjnetj“:“asd“
  }
}
```

Response from server:

"{\"errors\":[{\"message\":\"There can be only one variable named \\\"_1imzpym4atbyu\\\".\",\"locations\":[{\"line\":1,\"column\":12},{\"line\":1,\"column\":38}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\",\"exception\":{\"stacktrace\":[\"GraphQLError: There can be only one variable named \\\"_1imzpym4atbyu\\\".\",\"    at Object.VariableDefinition (/app/node_modules/graphql/validation/rules/UniqueVariableNames.js:31:29)\",\"    at Object.enter (/app/node_modules/graphql/language/visitor.js:324:29)\",\"    at Object.enter (/app/node_modules/graphql/language/visitor.js:375:25)\",\"    at visit (/app/node_modules/graphql/language/visitor.js:242:26)\",\"    at Object.validate (/app/node_modules/graphql/validation/validate.js:73:24)\",\"    at validate (/app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)\",\"    at Object.<anonymous> (/app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)\",\"    at Generator.next (<anonymous>)\",\"    at fulfilled (/app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)\",\"    at runMicrotasks (<anonymous>)\",\"    at processTicksAndRejections (internal/process/task_queues.js:93:5)\"]}}}]}\n"

Is this optimization intentional? Seems like our server does not like that.

If I am passing email and password as non-identical values then everything works correctly.

Thanks!

**Comment by maticzav** [comment]
Thank you for opening the issue. I'll try to fix this by the end of the week. I hope it doesn't block you in any way. 

I am very excited to see you using the library. Let me know if you find anything else strange. Feel free to open a discussion about any feature or design change if you have any suggestions.

**Comment by justvil** [comment]
Thanks @maticzav , looking forward to the fix!

**Comment by maticzav** [comment]
Hey! This has been fixed in the `next` branch. There are some changes that we'll introduce, but I think all code should be backward compatible. You might need to modify a bit the generated code, but not significantly.
