### ISSUE TITLE
Error: unknownScalar("DateTime")

### ISSUE THREAD

**Issue by quentinfasquel** [maticzav/swift-graphql#31]
**Describe the bug**
Hi there, I've been trying to get the GraphQL schema from an endpoint but it the command-line client `swift-graphql` fails on that endpoint where Apollo Client works fine. I followed your explanation passing a `.yml` with the following content :
```
scalars:
  Date: DateTime
  Upload: Upload
```

.. but I still get the error.

**To Reproduce**
`swift-graphql https://my_hostname/my_graphql_endpoint`
OR
`swift-graphql https://my_hostname/my_graphql_endpoint --config swiftgraphql.yml`

Any clue ?

**Comment by maticzav** [comment]
Is it possible that the scalar type in your schema is `DateTime`, not `Date`?

**Comment by quentinfasquel** [comment]
Well.. It seems that I have plenty other scalar types... what I don't explain is why the appolo command-line doesn't require any config..

**Comment by maticzav** [comment]
I think Apollo CLI doesn't let you define custom scalars, but I might be wrong. It's on our to-do list to generate default implementations of that type, but you have to specify them for now explicitly.

---

I don't think it's beneficial to pose questions in lines of _that tool does something that this one doesn't_. I mean, _we know_, you've been here for less than an hour, and I spent weeks working on it. You can consider sponsoring it and request a feature. This way, it might get added sooner.

**Comment by quentinfasquel** [comment]
@maticzav thank you.

> I don't think it's beneficial to pose questions in lines of _that tool does something that this one doesn't_. I mean, _we know_, you've been here for less than an hour, and I spent weeks working on it. You can consider sponsoring it and request a feature. This way, it might get added sooner.

I didn't mean like that. I am fairly new to using GraphQL and I just figured, right before my reply, that I could query a "_schema" that returns all the scalar types used by the endpoint I'm working with, which I thought was powerful. Therefore I thought it was automatic to retrieve both schema and custom scalar types. Now I get it, it's not and I would love to help on the subject but that's out of my available time. Please know that I really appreciate the efforts spent on this library and I hope to use it soon.
