### ISSUE TITLE
Multiple queries on the same socket

### ISSUE THREAD

**Issue by Amzd** [maticzav/swift-graphql#34]
Right now we create a new websocket for each query which is quite performant heavy and not necessary.

You can send multiple queries on one socket. You then define the results that you get back per id.

We'll need to change the `listen` part quite a lot for this so I'm looking for some feedback on how we should do it.

### We need a way to share a socket between `listen` calls

So either;

1. Save a socket for each endpoint without the user seeing them in a static variable or something.
2. Have the user handle the socket; so have a createWebsocket function that gives the user an opened socket that they can give to the listen function.

### The listen call needs to return something that you can use to stop that single query that you started.

In the listen call I will add an id to the message (this was already commented). To stop a query from listening you need its id so we could;

1. Just return the id and have a function to stop listening per id.
2. Return an object that has a close function to stop listening to its query.

**Comment by Amzd** [comment]
This and #32 are fixed in https://github.com/Amzd/swift-graphql/tree/WebSockets-rework

Some work that still has to be done:

- Move classes out of HTTP+WebSockets.swift to their own files
- Test serverside errors. The protocol says it returns GraphQLError[] which I assumed is an array of our GraphQLError type so I decode it as such.

**Comment by maticzav** [comment]
@Amzd could you create a PR so we can move this here as well?
