### ISSUE TITLE
Why not use dataTaskPublisher

### ISSUE THREAD

**Issue by NeverwinterMoon** [maticzav/swift-graphql#37]
I see that you have Combine as a dependency in the HTTP module and yet you are not using `URLSession#dataTaskPublisher(for:)` and rely on callbacks. Would be awesome to have `AnyPublisher<Value, Error>` returned from `HTTP#send`

**Comment by maticzav** [comment]
This sounds like a great idea. Could you create a PR?

**Comment by Amzd** [comment]
Not sure why we import Combine there since it's not actually used. `dataTaskPublished(for:)` is iOS 13+ and macOS 10.15+ so we'd have to have the current send methods AND a publisher version.

**Comment by NeverwinterMoon** [comment]
Current minimum iOS version for this library is 13 and macOS 10.15 as far as I see.  So nothing is stopping from having just the Publisher version.

**Comment by NeverwinterMoon** [comment]
Oh, you were faster than me :)

**Comment by Amzd** [comment]
Hmm, not sure why the Package is iOS 13+. I'm using it through private cocoapods release on iOS 12 too so for me removing the current send methods would strand me on the older versions 😆

**Comment by maticzav** [comment]
@NeverwinterMoon we are planning to address this issue in the next couple of days. Could you maybe share a couple of examples of the desired API (e.g. return types, function calls) and docs related to Combine functionality that we'd use?

**Comment by NeverwinterMoon** [comment]
@maticzav Hi! Sorry for the delay reply.

## Implementation
I'll show what I myself implemented really quickly when using your neat library.  Most probably you don't want to go this way and instead implement `dataTaskPublisher`. Example of this follows

```swift
func send<Type, TypeLock: GraphQLHttpOperation & Decodable>(
    _ selection: Selection<Type, TypeLock>
  ) -> AnyPublisher<Type, Error> {

/// Most probably, needs to be wrapped in Deferred (https://developer.apple.com/documentation/combine/deferred)
/// as Future will produce a result immediately when called (even if there is no subscriber)
/// in my case I never call this without a subscriber, so I didn't bother with Deferred 
  Future<GraphQLResult<Type, TypeLock>, Error> { promise in
      send(selection, to: baseURL, headers: ["Authorization": "Bearer \(jwt)"]) { result in
        switch result {
          case .success(let result):
            promise(.success(result))

          case .failure(let error):
            promise(.failure(error))
        }
      }
    }
      .tryMap { result in
        result.data
      }
      .eraseToAnyPublisher()
  }
```

Here is how I see the implementation using `dataTaskPublisher`:

```swift
let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 60
configuration.timeoutIntervalForResource = 120
configuration.waitsForConnectivity = true
configuration.httpMaximumConnectionsPerHost = 5
let session = URLSession(configuration: configuration)

guard let url = URL(string: "https://intotheunknown") else {
  throw APIError.invalidURL
}
let urlRequest = URLRequest(url: url)
/// urlRequest configuration

/// to validate expected response code, here we expect success only
let httpCodes: Range<Int> = 200..<300

let decoder: JSONDecoder = {
  let decoder = JSONDecoder()
  decoder.dateDecodingStrategy = .iso8601

  return decoder
}()

/// This tries to decode the result
session
  .dataTaskPublisher(for: request)
  .tryMap {
    guard let code = (output.response as? HTTPURLResponse)?.statusCode else {
      throw APIError.unexpectedResponse
    }

    guard httpCodes.contains(code) else {
      throw APIError.httpCode(code)
    }

    return output.data
  }
  .mapError {
    (($0 as NSError).userInfo[NSUnderlyingErrorKey] as? Failure) ?? $0
  }
  /// https://developer.apple.com/documentation/combine/fail/decode(type:decoder:)
  .decode(type: Value.self, decoder: decoder)
  .receive(on: DispatchQueue.main)
  .eraseToAnyPublisher()

```

## Usage
Something like this:

```swift
let someMutation = Selection<(), Objects.Mutation> { ... }

send(someMutation)
      .print("GQL")
      .ignoreOutput()
      .sink(receiveCompletion: { _ in }, receiveValue: { _ in })
      .store(in: cancelBag)
```

Also, I am more than willing to give PR a whirl, if you still think it's a good idea.

**Comment by maticzav** [comment]
I am going to close this issue since the new version heavily relies on Combine. 

I think @NeverwinterMoon's answer can still help people using only the library's core, but we no longer make any assumptions on how you perform your `URLRequest` there.
