### ISSUE TITLE
Error running codegen using commercetools GraphQL API

### ISSUE THREAD

**Issue by drhaynes-wigglecrc** [maticzav/swift-graphql#41]
**Describe the bug**

When trying to run codegen against the [commercetools GraphQL API](https://docs.commercetools.com/api/graphql) endpoint, the process halts with error:

> Cannot get unkeyed decoding container -- found null value instead.

This looks to be an error parsing / decoding the returned schema.

**To Reproduce**

```
$ swift-graphql "https://api.europe-west1.gcp.commercetools.com/insert-instance-name-here/graphql" --authorization "Bearer <auth token here>"
```

Doing this, we get errror: 

```
Error: valueNotFound(
	Swift.UnkeyedDecodingContainer,
	Swift.DecodingError.Context(
		codingPath: 
			CodingKeys(stringValue: "data", intValue: nil),
			CodingKeys(stringValue: "__schema", intValue: nil)
			CodingKeys(stringValue: "types", intValue: nil),
			_JSONKey(stringValue: "Index 71", intValue: 71),
			CodingKeys(stringValue: "interfaces", intValue: nil)
		debugDescription: "Cannot get unkeyed decoding container -- found null value instead.", underlyingError: nil
	)
)
```

**Expected behavior**

Codegen runs without error

**Comment by AlexGustafsson** [comment]
Same with https://api.github.com/graphql.

**Comment by maticzav** [comment]
yea, so do you maybe know if the issue is with authentication or with parsing?

**Comment by paambaati** [comment]
We're also facing the same issue here – https://github.com/maticzav/swift-graphql/discussions/67. Can confirm the issue is not with authentication.
