### ISSUE TITLE
Generator butchers type names in some cases

### ISSUE THREAD

**Issue by NeverwinterMoon** [maticzav/swift-graphql#42]
**Describe the bug**
```swift
enum TypeName: String, Codable {
   case firmwareNrfmTadata = "FirmwareNRFMetadata"
}
```
Why not preserve the name as it is?

I've also noticed this (which is not as bad as the first example):
```
func dateIso() throws -> String {
        let field = GraphQLField.leaf(
            name: "dateISO",
            arguments: []
        )
       ...
}
```

Using names like `dateISO` or `FirmwareNRFMetadata` is a pretty standard convention in the Swift world, as far as I know...

**Comment by maticzav** [comment]
@NeverwinterMoon 👋 ,

Thank you for pointing this out. I am not sure what the thinking process was behind making the converter. I think I'll just move everything back to how user exports it.

**Comment by NeverwinterMoon** [comment]
Not 100% sure it's related, but looks like it is.

So, I have the following payload created by `let payload = selection.buildPayload(operationName: operationName)`

`"query ($__1gxyzmx97f4f1: String!) {\n  bikeStatisticsG2CRrentWeekSummary___9sez2m4ezyv2: bikeStatisticsG2CurrentWeekSummary(id: $__1gxyzmx97f4f1) {\n    __typename\n    ...on BikeStatisticsSummary {\n      distanceKm___1utcuuc57whji: distanceKm\n      timeSec___1utcuuc57whji: timeSec\n    }\n    ...on ErrorWithMessage {\n      message___1utcuuc57whji: message\n    }\n  }\n}"`

The response received is this (string from data in response):
`"{\"data\":{\"bikeStatisticsG2CRrentWeekSummary___9sez2m4ezyv2\":{\"__typename\":\"BikeStatisticsSummary\",\"distanceKm___1utcuuc57whji\":0.06999999999999999,\"timeSec___1utcuuc57whji\":44}}}\n"`

The deserialization fails. If I change the name of the query on the back-end to something simpler, change the selector names in Swift code accordingly and leave the rest of the code unchanged, it works...

**Comment by NeverwinterMoon** [comment]
@maticzav Maybe a naïve question, but why is camel-casing needed at all in this case?
```
public var alias: String? {
// ....
   return "\(name.camelCase)_\(arguments.hash)"
// ....
}
```
