### ISSUE TITLE
Support for CocoaPods

### ISSUE THREAD

**Issue by racer1988** [maticzav/swift-graphql#44]
**Is your feature request related to a problem? Please describe.**

We are unable to use SPM in our project so we would like to use this framework over CocoaPods

**Describe the solution you'd like**
Publish the framework on CocoaPods

**Comment by maticzav** [comment]
@racer1988 could you point me to the right docs so I can merge your PR? Or is it ready to be merged?

**Comment by racer1988** [comment]
added info in #45

**Comment by maticzav** [comment]
Closing this issue since the new version added Podspec file. Feel free to reopen the issue if it doesn't work correctly.
