### ISSUE TITLE
Support for async/await

### ISSUE THREAD

**Issue by jacobhzen** [maticzav/swift-graphql#51]
Support for Swift 5.5's new async/await would be amazing.

**Comment by NeverwinterMoon** [comment]
Yep, I would love that, too. Now it’s official: async/await backward compatible down to iOS 13: https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes

**Comment by Amzd** [comment]
This should be as simple as wrapping the send function with `withCheckedThrowingContinuation`. Don’t think it applies to the websockets.

**Comment by Amzd** [comment]
Correction; We can implement AsyncSequence for web sockets: https://obscuredpixels.com/awaiting-websockets-in-swiftui

But this is not as trivial as the send functions so I would make this a separate issue.

**Comment by maticzav** [comment]
Hi everyone 👋 ,

I am happy to co-work on this feature now that the new version is out. Let me know if anyone wants to give it a try!

**Comment by elfenlaid** [comment]
@maticzav Sounds interesting! I would like to give it a try 🙏 

Tho, seems a lot changed since the initial discussion had kicked off. Please correct me if I'm wrong, but it seems that introducing async/await in the current version's context means extending the following functions with async analogous:

```swift
public class Client: GraphQLClient, ObservableObject {
    // ...
    public func query(
        _ args: ExecutionArgs,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> Source {
       // ...
    }

    // ...
    public func mutate(
        _ args: ExecutionArgs,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> Source {
    // ...
    }
 
    // ...
    public func subscribe(
        _ args: ExecutionArgs,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> Source {
    // ...
    }
}
```

Also I must note that Combine provides a binding to async/await out-of-box:

```swift
let publisher = remoteDataPublisher(forURLs: urls)

for try await data in publisher.values { // AsyncThrowingSequence
    ...
}
```

(Source ☝️  [Async sequences, streams, and Combine | Swift by Sundell](https://www.swiftbysundell.com/articles/async-sequences-streams-and-combine/))

That said, it seems that we can extend the Client's API by introducing one-shot throwing async versions of `query` and `mutate`. As for `subscription` we can provide a version that returns `AsyncThrowingStream` as out of convenience  🤔 

Please let me know what do you think about it 🙇

**Comment by maticzav** [comment]
@elfenlaid, you are right! Let me know if you are still interested, your comment must have slipped through the cracks of my inbox ☹️

**Comment by elfenlaid** [comment]
@maticzav yeap, on it then 🙇

**Comment by elfenlaid** [comment]
I'm so sorry, but I'll park the ticket for now 🙇

**Comment by pokryfka** [comment]
for my needs I just created an extension 

```swift
import struct Foundation.URLRequest
import SwiftGraphQL
import SwiftGraphQLClient

public extension GraphQLClient {
    func queryAsync<T, TypeLock>(
        _ selection: Selection<T, TypeLock>,
        as operationName: String? = nil,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> AsyncThrowingStream<DecodedOperationResult<T>, any Error> where TypeLock: GraphQLHttpOperation {
        query(selection, as: operationName, request: request, policy: policy)
            .values
            .eraseToThrowingStream()
    }

    func mutateAsync<T, TypeLock>(
        _ selection: Selection<T, TypeLock>,
        as operationName: String? = nil,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> AsyncThrowingStream<DecodedOperationResult<T>, Error> where TypeLock: GraphQLHttpOperation {
        mutate(selection, as: operationName, request: request, policy: policy)
            .values
            .eraseToThrowingStream()
    }

    func subscribeAsync<T, TypeLock>(
        to selection: Selection<T, TypeLock>,
        as operationName: String? = nil,
        request: URLRequest? = nil,
        policy: Operation.Policy = .cacheFirst
    ) -> AsyncThrowingStream<DecodedOperationResult<T>, Error> where TypeLock: GraphQLWebSocketOperation {
        subscribe(to: selection, as: operationName, request: request, policy: policy)
            .values
            .eraseToThrowingStream()
    }
}
```

**Comment by pokryfka** [comment]
For the record, and in case its useful, somehow I thought `eraseToThrowingStream()` is part of Swift but I had it in already imported `swift-concurrency-extra` packaged:

https://github.com/pointfreeco/swift-concurrency-extras/blob/main/Sources/ConcurrencyExtras/AsyncThrowingStream.swift

--

Also note that while in case of mutations arguably cached results should not be used, for queries with `policy` set to `.cacheAndNetwork` there may be two values returned, see https://github.com/maticzav/swift-graphql/pull/105#discussion_r1348624662
