### ISSUE TITLE
Github Actions are not publishing new versions to Brew. (also SPM can't automatically resolve)

### ISSUE THREAD

**Issue by racer1988** [maticzav/swift-graphql#58]
Installing via Brew:

`Downloading https://github.com/maticzav/swift-graphql/archive/2.0.0.tar.gz`

Seems that after 2.0.0 you are using Github Actions for releases after each merge.
This is great but it seems to break Brew.

I also had trouble using SPM, I add to provide exact version to resolve it the first time, else it did not found the standard version published in the package

**Comment by maticzav** [comment]
Thanks!! This issue should be resolved with the new version of SwiftGraphQL.

Feel free to reopen the this issue if you still have problems and I'll help you out 🙂.
