### ISSUE TITLE
Expose a boolean `mock` property in selection

### ISSUE THREAD

**Issue by maticzav** [maticzav/swift-graphql#64]
Right now, it's hard to verify data in the query when data contains a particular format of 

- a string (URL for example), 
- an array (might be a non-empty array),
- optional value (might always be there).

To consider the problem, we should expose a `$0.decoding` boolean value that is `false` when the query is building and `true` when we are actually decoding the data.

**Comment by Amzd** [comment]
I would propose a state enum with two cases; building and decoding.
