### ISSUE TITLE
Apostrophes in descriptions trigger generator error

### ISSUE THREAD

**Issue by shmanny** [maticzav/swift-graphql#65]
**Describe the bug**
Descriptions containing apostrophes throws: 
```
Error: Unexpected token 's at 123:39
```
upon generating Swift via swift-graphql

**To Reproduce**
Add a documented type to schema:
```
input AuthenticateInput {
  """User's registered email"""
  email: String!
  }
  ```
 Confirm that the description is valid and then try to generate swift:
 `swift-graphql http://localhost:8000/query`

**Expected behavior**
Swift output

**Comment by maticzav** [comment]
Hey there!

Thank you for opening this issue. I am going to close it because I think we've solved it in the new version that was just released but feel free to reopen it if you still have trouble, and I'll make sure we resolve it.
