### ISSUE TITLE
`make install` fails

### ISSUE THREAD

**Issue by pepas-everly** [maticzav/swift-graphql#71]
Installing `swift-graphql` (either through homebrew or `make install`) currently fails to build:

```
/private/tmp/SwiftGraphQL-20220315-23016-185y7qo/swift-graphql-2.3.0/.build/checkouts/SwiftFormat/Sources/CommandLine.swift:556:44: error: 'temporaryDirectory' is only available in macOS 10.12 or newer
                return FileManager.default.temporaryDirectory
```

**Comment by maticzav** [comment]
Hey there! Thank you for opening this up. What's your Mac OS version? I think you might have to upgrade your system.

**Comment by pepas-everly** [comment]
Perhaps the deployment target of some of the dependencies is set less than 10.2?

**Comment by CooperWolfe** [comment]
I found the following issue, which seems to be causing this one:
https://github.com/nicklockwood/SwiftFormat/issues/1158

**Comment by CooperWolfe** [comment]
@pepas-everly I made a [fork](https://github.com/CooperWolfe/SwiftFormat) in the meantime of either my PR merging or the root problem being fixed if this is mission critical for you.

**Comment by pepas-everly** [comment]
@CooperWolfe oh thank you so much!  It isn't super critical, I just wanted to evaluate it because it looked like an attractive alternative to Apollo, but I can certainly wait a few days for a fix to be merged in.
