### ISSUE TITLE
Error: unknownScalar("JSON")

### ISSUE THREAD

**Issue by ZsoltMolnarMBH** [maticzav/swift-graphql#73]
**Describe the bug**
Running the code generator on a remote schema with "JSON" as scalar procudes error.

**To Reproduce**
Try to generate swift code from a schema that has `JSON` scalar fields.
For example:
```
{
  "name": "documents",
  "description": null,
  "args": [],
  "type": {
    "kind": "SCALAR",
    "name": "JSON",
    "ofType": null
  },
  "isDeprecated": false,
  "deprecationReason": null
},
```

**Expected behavior**
I am not sure what should happen.
Is this an illegal schema? If so, can you point to any official guideline/recommendation that I can send to our backend developers?

**Comment by wambambizzle** [comment]
Just ran into this myself and there is a pretty simple solution

If you already have a `swiftgraphql.yml` for generating your schema with `swift-graphql your-grahpql-api-url --config swiftgraphql.yml -o Schema.swift`

You can add this file `swiftgraphql.yml` with:
```
scalars:
  JSON: String
```

**Comment by maticzav** [comment]
Thanks @wambambizzle for giving the quick answer!

The new version now doesn't error on unknown scalars and defaults to `AnyCodable` value.

Let me know how it goes when you try it out!
