### ISSUE TITLE
Cannot convert value of type 'String?' to type 'OptionalArgument<String>'

### ISSUE THREAD

**Issue by wambambizzle** [maticzav/swift-graphql#76]
**Describe the bug**

Forced to cast optional values with `OptionalArgument(some-value)` instead of being able to pass swift optionals directly inside of `Selection.Mutation`'s

The Error(s):
`Cannot convert value of type 'String?' to expected argument type 'OptionalArgument<String>' or
Cannot convert value of type '[String]?' to expected argument type 'OptionalArgument<[String]>'`  when trying to pass optional values to a `Selection.Mutation`

**To Reproduce**

```
struct UserDao: Identifiable {
  let id: String
  let name: String?
}

struct CreateUser {
  let user: UserDao
  let errors: [String]
}

struct UserForm {
  let id: String
  let name: String?
}

private static func userSelection() -> Selection<UserDao, Objects.User> {
    return  Selection.User {
      UserDao(id: try $0.id(), name: try $0. name())
  }
}

static func updateUser(form: UserForm) {
   let user = userSelection()

   let updateUser = Selection.UpdateUserPayload { u in
      CreateUser(user: try u.user(selection: user), errors: try u.errors())
   }

  // Name errors here
  let query = Selection.Mutation {
      try $0.updateUser(id: form.id, name: name, selection: updateUser.nullable)
  }

  // If changed to below it will work fine:
  let name = OptionalArgument(form.name)
  let query2 = Selection.Mutation {
       try $0.updateUser(id: form.id, name: name, selection: updateUser.nullable)
   }
}

```

**Expected behavior**
Expect to be able to pass swift optional types directly into the Selection Mutation without conversion.

**Screenshots**
n/a

**Smartphone (please complete the following information):**

- Device: iPhone 12 simulator
- OS: iOS 12
- Browser: n/a
- Version n/a

**Additional context**
Maybe this is working as intended and should be a feature request/enhancement

**Comment by maticzav** [comment]
Hey 👋 !

Thank you for opening this issue! Yea, it's not exactly a feature but not a bug either. `OptionalArgument` is not exactly the same as a Swift `Optional` value.  I suggest you check out the docs that have an updated section on OptionalArgument type https://www.swift-graphql.com/docs/querying#optional-arguments.

> If you are curious why we need a completely different structure to represent optional values, it's because the way `OptionalArgument` is implemented, it can self-reference itself, which is a common thing in the input parameters of the GraphQL schemas (e.g. a filtering tree structure that references itself).
