### ISSUE TITLE
Subscriptions listen-method not available

### ISSUE THREAD

**Issue by CemYil03** [maticzav/swift-graphql#78]
Trying to make a subscription I discovered, that listen is not a method available after `import SwiftGraphQL`. Instead it tries to use a listen function with the following signature: `listen(Int32, Int32) -> Int32`

Maybe it is just about declaring it public?

A reproduction should be simple. Sadly there was also no example in the examples directory. If I am doing something wrong maybe it would be nice to see an example there. The one from the documentation simply does not work for me.

**Comment by maticzav** [comment]
👋 the new version ships with a full-blown WebSocket client. You can read more about it at https://www.swift-graphql.com/docs/subscriptions.

I am going to close the issue but feel free to comment on it and even reopen it, if you need more help 🙂
