### ISSUE TITLE
Dependency iOS/macOS dependency error on SwiftSyntax 

### ISSUE THREAD

**Issue by ijonas** [maticzav/swift-graphql#87]
**Describe the bug**
The latest version of SwiftGraphql seems to introduce a dependency compilation bug with the SwiftSyntax package. Both the main branch as well as version 4.0.0 cause the XCode compiler to throw the following error:

/Users/ijonas/Library/Developer/Xcode/DerivedData/Ojai2-fxyzrqzzubyxgybaukbsxawldlnn/SourcePackages/artifacts/swift-syntax/_InternalSwiftSyntaxParser.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/ijonas/Library/Developer/Xcode/DerivedData/Ojai2-fxyzrqzzubyxgybaukbsxawldlnn/SourcePackages/artifacts/swift-syntax/_InternalSwiftSyntaxParser.xcframework'.

**To Reproduce**

Launch XCode
Create a brand new "iOS App" project
Add the "https://github.com/maticzav/swift-graphql/" package (either main or 4.0.0)
Add all products except for "swift-graphql Executable"
Run the project (or run Build)

**Expected behavior**
Be able to add SwiftGraphql as a dependency on "iOS-only projects".

**Desktop (please complete the following information):**

MacOS 12.5.1
XCode 13.4.1

**Smartphone (please complete the following information):**

- Deployment Target: iOS 15.5
- Run on Simulator: iPod Touch 7th Gen

(These were just XCode project defaults)

**Comment by ashar340** [comment]
facing the same

**Comment by SilverTab** [comment]
Same issue here in a brand new project.
macOS 15.2
Xcode 13.4.1

**Comment by maticzav** [comment]
Thank you for opening the issue, I'll move the conversation to #93. 🙂
