### ISSUE TITLE
Support GraphQL SDL

### ISSUE THREAD

**Issue by Sundea** [maticzav/swift-graphql#88]
**Describe the bug**
I've downloaded the Github schema by link https://docs.github.com/en/graphql/overview/public-schema and then have tried to run the generator `% swift-graphql schema.docs.graphql` and it has failed

**To Reproduce**

1. Go to 'https://docs.github.com/en/graphql/overview/public-schema' and download the schema
2. run `% swift-graphql schema.docs.graphql`
3. See error 
```
Generating SwiftGraphQL Selection 🚀
⠋ Fetching GraphQL SchemaThe data couldn’t be read because it isn’t in the correct format.
Error: Couldn't reach GraphQL server at given endpoint.
```

**Comment by maticzav** [comment]
@Sundea thank you for reporting this, but this is not a bug or at least I wouldn't consider it.

The thing is that the generating works out of the JSON dump of the schema, but not yet out of the GraphQL DSL schema. Is this a blocker for you? I think it's not completely trivial to parse the schema DSL into the format that the generator expects, but I'd happily help you give it a stab 🙂

**Comment by VladimirLogachev** [comment]
Most GraphQL code generators work with SDL, so it's sort of expected.
But anyway, thank you for the explanation.
And for the library itself, too! 🤎

**Comment by Fedos** [comment]
I'd double that I also expected from Codegen to support SDL schema as an input, but I see that it's not trivial, so in the meantime I use this online SDL > JSON converter  https://transform.tools/graphql-to-introspection-json , the only thing missing in it's output is that you have to nest it in the "data" key.

BTW, @maticzav , would be nice if the integrations tests of the codegen used the schema from the file instead of using localhost server (which I haven't figured out how to run)
Here is the converted schema file for that:
[schema.json.zip](https://github.com/maticzav/swift-graphql/files/11991051/schema.json.zip)

**Comment by pokryfka** [comment]
> BTW, @maticzav , would be nice if the integrations tests of the codegen used the schema from the file instead of using localhost server (which I haven't figured out how to run) Here is the converted schema file for that: [schema.json.zip](https://github.com/maticzav/swift-graphql/files/11991051/schema.json.zip)

I echo that.

**Comment by shaps80** [comment]
💯

I'll make a new Issue to keep track of this 👍

**Comment by shaps80** [comment]
> > BTW, @maticzav , would be nice if the integrations tests of the codegen used the schema from the file instead of using localhost server (which I haven't figured out how to run) Here is the converted schema file for that: [schema.json.zip](https://github.com/maticzav/swift-graphql/files/11991051/schema.json.zip)
> 
> I echo that.

💯

I'll make a new Issue to keep track of this 👍

**Comment by shaps80** [comment]
After further discussion @maticzav and I have decided that this is fairly low priority given we're making a library for App users which will 99% of the time already have access to a GraphQL schema and as such can use introspection.

That being said, we have substantial plans in v6 to reduce code-generation times to seconds in almost all cases, so this may be less of an issue in the coming days.

We will re-review if and when further performance enhancements need to be met.
